# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12m9GZxrkmyXUPZg5Uqd5VBd_h5Q7TFuK
"""

'pip install gender_guesser'

import pandas as pd
import numpy as np
import random
from gender_guesser import detector

df = pd.read_csv('nombres_españoles.csv', sep = ';', header = None)
df = df.rename(columns={0: 'nombre', 1: 'apellido'})

df['edad'] = np.random.randint(65, 100, 50000)
df['discapacidad'] = np.random.randint(0, 2, 50000)
df['pension'] = np.random.randint(10963.40, 42829.29, 50000)
df['familia_numerosa'] = np.random.randint(0, 2, 50000)
df['edad_hijo'] = None
df['trabaja_hijo'] = None

fam_num_index = df[df['familia_numerosa'] == 1].index
for i in (fam_num_index):
    a = len(fam_num_index)
    df['edad_hijo'][i] = np.random.randint(15, 26)

hijo_mayor_index = df[df['edad_hijo'] > 20].index
for i in (hijo_mayor_index):
    a = len(hijo_mayor_index)
    df['trabaja_hijo'][i] = np.random.randint(0, 2)

df['lista_espera'] = np.random.randint(0, 3, 50000)

df['estado_civil'] = None
estados = ['soltero/a', 'casado/a', 'viudo/a']
for i in (df.index):
    df['estado_civil'][i] = random.choice(estados)

df['años_ant'] = np.random.randint(0, 3, 50000)
df['vehiculo'] = np.random.randint(0, 2, 50000)
df['hab_individual'] = np.random.randint(0, 2, 50000)

df['mobilidad'] = None
mobilidad = ['perfecta', 'media', 'limitada']
for i in (df.index):
    df['mobilidad'][i] = random.choice(mobilidad)

df['enfermedad'] = None
enfermedad = ['None', 'terminal']
enfermedad = ['None'] * 99 + ['terminal'] * 1
for i in (df.index):
    df['enfermedad'][i] = random.choice(enfermedad)

df['sexo'] = None
gender_detector = Detector()
df['nombre'] = df['nombre'].astype('str')
df['nombre'] = df['nombre'].apply(lambda x: x.title())
df['apellido'] = df['apellido'].astype('str')
df['apellido'] = df['apellido'].apply(lambda x: x.title())
for i in (df.index):
    df['sexo'][i] = gender_detector.get_gender(df['nombre'][i])

df['trabajo'] = None
trabajos = [
    "Médico",
    "Enfermero/a",
    "Profesor/a",
    "Ingeniero/a",
    "Abogado/a",
    "Arquitecto/a",
    "Administrativo/a",
    "Comercial/Vendedor/a",
    "Electricista",
    "Fontanero/a",
    "Programador/a informático/a",
    "Diseñador/a gráfico/a",
    "Carpintero/a",
    "Fontanero/a",
    "Cocinero/a",
    "Camarero/a",
    "Agricultor/a",
    "Peluquero/a",
    "Fontanero/a",
    "Operario/a de fábrica"
]
for i in (df.index):
    df['trabajo'][i] = random.choice(trabajos)

df['pension'] = np.random.randint(6784.54, 42829.29, 50000)



bins = [6774.54, 12600, 14700, 16800, 18900, 21000, 23100, 25200, 27300, 29400, float('inf')]
etiquetas = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
df['tipo_pension'] = pd.cut(df['pension'], bins=bins, labels=etiquetas)

